Using cpu device
Logging to runs/bosjb192\A2C_1
Traceback (most recent call last):
  File "d:/RLinGUD/SOS_MDP/train.py", line 49, in <module>
    model.learn(total_timesteps=config["total_timesteps"],
  File "C:\Users\zeina\anaconda3\envs\sosRL\lib\site-packages\stable_baselines3\a2c\a2c.py", line 191, in learn
    return super(A2C, self).learn(
  File "C:\Users\zeina\anaconda3\envs\sosRL\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 250, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "C:\Users\zeina\anaconda3\envs\sosRL\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 178, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
  File "C:\Users\zeina\anaconda3\envs\sosRL\lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py", line 162, in step
    return self.step_wait()
  File "C:\Users\zeina\anaconda3\envs\sosRL\lib\site-packages\stable_baselines3\common\vec_env\vec_video_recorder.py", line 88, in step_wait
    obs, rews, dones, infos = self.venv.step_wait()
  File "C:\Users\zeina\anaconda3\envs\sosRL\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 43, in step_wait
    obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
  File "C:\Users\zeina\anaconda3\envs\sosRL\lib\site-packages\stable_baselines3\common\monitor.py", line 90, in step
    observation, reward, done, info = self.env.step(action)
  File "d:\RLinGUD\SOS_MDP\envs.py", line 355, in step
    reward += node_connectivity(self.graph)  # connectivity reward
  File "C:\Users\zeina\anaconda3\envs\sosRL\lib\site-packages\networkx\algorithms\approximation\connectivity.py", line 197, in node_connectivity
    if not connected_func(G):
  File "C:\Users\zeina\anaconda3\envs\sosRL\lib\site-packages\networkx\utils\decorators.py", line 845, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 4", line 4, in argmap_is_connected_1
    import inspect
  File "C:\Users\zeina\anaconda3\envs\sosRL\lib\site-packages\networkx\algorithms\components\connected.py", line 142, in is_connected
    raise nx.NetworkXPointlessConcept(
networkx.exception.NetworkXPointlessConcept: ('Connectivity is undefined ', 'for the null graph.')